apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKeyBase: {{ .Values.deploy.secretKeyBase | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.auth.database | b64enc | quote }}
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{end}}
  sentryDsn: {{ .Values.sentry.dsn | b64enc | quote }}
  ccmsSoaAwsGatewayApiKey: {{ .Values.ccms_soa.awsGatewayApiKey | b64enc | quote }}
  ccmsSoaClientUsername: {{ .Values.ccms_soa.clientUsername | b64enc | quote }}
  ccmsSoaClientPasswordType: {{ .Values.ccms_soa.clientPasswordType | b64enc | quote }}
  ccmsSoaClientPassword: {{ .Values.ccms_soa.clientPassword | b64enc | quote }}
  ccmsSoaUserRole: {{ .Values.ccms_soa.userRole | b64enc | quote }}
  ccmsSoaGetCommonOrgWsdl: {{ .Values.ccms_soa.getCommonOrgWsdl | b64enc | quote }}
  ccmsSoaProviderUsername: {{ .Values.ccms_soa.providerUsername | b64enc | quote }}
