apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.auth.database | b64enc | quote }}
  {{end}}
