version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
      timezone: Europe/London
    groups:
      bundler:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "ministryofjustice/laa-apply-for-legal-aid"
