version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
      timezone: Europe/London
    groups:
      bundler:
        patterns:
          - "*"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: friday
      time: "05:00"
