repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: 5b00ab6401ed59fa55ff76b32cf8027c920cef46 # v2.0.1 re-run prek install after changing this
    hooks:
      - id: baseline
  - repo: local
    hooks:
      - id: rubocop
        name: Rubocop
        language: system
        entry: bundle exec rubocop --force-exclusion
