plugins:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*'

Lint/RedundantDirGlobSort:
  Exclude:
    - 'db/seeds.rb'

Rails/I18nLocaleTexts:
  Exclude:
    - 'app/models/client_involvement_type.rb'
    - 'app/models/scope_user_input.rb'

Naming/PredicateMethod:
  Exclude:
    - 'app/services/questions_service.rb'
    # excluding the question service as the cop is currently (Jul 2025) flagging some
    # predicate questions, but not all.  As the methods are all called the same way and
    # not called by anything other than the yaml blocks, this seems a bit OTT to have to
    # rebuild all the yaml and DB interactions for a cop

# Swagger exclusions
# ==================
# because swagger does not use the standard RSpec layout, e.g.
# context 'when x'
#   describe 'and page submits'
#     it 'displays'
# etc, these RSpec cops are complaining. Therefore we are excluding the
# following so that the RSpec cops do not fail, but the remaining ones
# continue to monitor
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/**/*swagger*_spec.rb'
