plugins:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*'

Lint/RedundantDirGlobSort:
  Exclude:
    - 'db/seeds.rb'

Rails/I18nLocaleTexts:
  Exclude:
    - 'app/models/client_involvement_type.rb'
    - 'app/models/scope_user_input.rb'

# Swagger exclusions
# ==================
# because swagger does not use the standard RSpec layout, e.g.
# context 'when x'
#   describe 'and page submits'
#     it 'displays'
# etc, these RSpec cops are complaining. Therefore we are excluding the
# following so that the RSpec cops do not fail, but the remaining ones
# continue to monitor
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/**/*swagger*_spec.rb'
