version: 2.1

orbs:
  slack: circleci/slack@3.4.2
executors:
  basic-executor:
    docker:
      - image: cimg/base:2020.01
  cloud-platform-executor:
    docker:
      - image: ministryofjustice/cloud-platform-tools:1.23
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-apply-for-legal-aid
  linting-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - TZ: "Europe/London"
  notification-executor:
    docker:
      - image: 'cibuilds/base:latest'
        environment:
          TERM: dumb
    resource_class: small
  test-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - PGHOST=localhost
          - PGUSER=user
          - TZ: "Europe/London"
      - image: postgres:10.5
        environment:
          - POSTGRES_USER=user
          - POSTGRES_DB=legal-framework-api-test
references:
  build_docker_image: &build_docker_image
    run:
      name: Build application Docker image
        command: |
          $(aws ecr get-login --no-include-email)
          docker build \
          --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
          --build-arg BUILD_TAG="app-${CIRCLE_SHA1}" \
          --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
          -t app .
  push_to_ecr: &push_to_ecr
    run:
      name: Push image to ecr repo
      command: |
        docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"
        docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "main" ]; then
          docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
          docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
        fi
  setup_aws_login: &setup_aws_login
    run:
      name: Setup aws login
      command: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli
        $(aws ecr get-login --region eu-west-2 --no-include-email)
  setup_kubectl: &setup_kubectl
    run:
      name: Kubectl deployment setup UAT for LFA
      command: |
        $(aws ecr get-login --region eu-west-2 --no-include-email)
        setup-kube-auth
  update_packages: &update_packages
    run:
      name: Update packages
      command: sudo apt-get update
  install_packages_for_testing: &install_packages_for_testing
    run:
      name: Install System packages needed for testing
      command: sudo apt-get install -y postgresql-client
  install_git_crypt: &install_git_crypt
    run:
      name: Install git-crypt
      command: sudo apt-get install -y git-crypt
  decrypt_secrets: &decrypt_secrets
    run:
      name: Decrypt secrets file
      command: |
        echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
        git-crypt unlock git-crypt.key
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      keys:
        - legal-framework-api-{{ checksum "Gemfile.lock" }}
        - legal-framework-api
  install_gems: &install_gems
    run:
      name: Install ruby gems
      command: |
        gem install bundler -v 2.0.2
        bundle install --without development --path=vendor/bundle --jobs=4 && bundle clean
  save_gems_cache: &save_gems_cache
    save_cache:
      key: legal-framework-api-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  install_js_packages: &install_js_packages
    run:
      name: Install npm packages
      command: npm install
  setup_database: &setup_database
    run:
      name: Database Setup
      command: |
        bundle exec rake db:create db:schema:load
        bundle exec rake db:migrate
commands:
  hold-notification:
    description: Notify Slack about an awaiting approval job
    parameters:
      message:
        default: "$CIRCLE_USERNAME has a pending approval for $CIRCLE_BRANCH"
        description: A workflow in CircleCI is awaiting approval.
        type: string
      url:
        default: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
        description: The URL to link back to.
        type: string
      webhook:
        default: '${SLACK_WEBHOOK}'
        description: >-
          Enter either your Webhook value or use the CircleCI UI to add your token
          under the 'SLACK_WEBHOOK' env var
        type: string
    steps:
      - slack/approval:
          message: << parameters.message >>
          webhook: << parameters.webhook >>
jobs:
  lint_checks:
    executor: linting-executor
    steps:
      - checkout
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - run:
          name: Run Rubocop
          command:  bin/rails rubocop
  unit_tests:
    executor: test-executor
    steps:
      - checkout
      - *install_packages_for_testing
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - *setup_database
      - *install_js_packages
      - run:
          name: Run ruby tests
          command: bin/rails spec
  build_and_push:
    executor: basic-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - *update_packages
      - *install_git_crypt
      - *decrypt_secrets
      - *build_docker_image
      - *setup_aws_login
      - *push_to_ecr
  deploy_uat: &deploy_uat
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *setup_kubectl
      - run:
          name: Set kubectl context
          command: kubectl config use-context uat
      - *decrypt_secrets
      - deploy:
          name: Helm deployment to UAT
          command: |
            ./bin/uat_deploy
#  deploy_master_uat:
#    <<: *deploy_uat
#  delete_uat_branch:
#    executor: cloud-platform-executor
#    steps:
#      - checkout
#      - setup_remote_docker
#      - *setup_kubectl
#      - run:
#          name: Set kubectl context
#          command: kubectl config use-context uat
#      - run:
#          name: Delete UAT release
#          command: |
#            ./bin/delete_uat_release.sh
#  deploy_staging:
#    executor: cloud-platform-executor
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - *setup_kubectl
#      - run:
#          name: Set kubectl context
#          command: kubectl config use-context staging
#      - *decrypt_secrets
#      - deploy:
#          name: Helm deployment to staging
#          command: |
#            helm upgrade legal-framework-api ./deploy/helm/. \
#                          --install --wait \
#                          --namespace=${KUBE_ENV_STAGING_NAMESPACE} \
#                          --values ./deploy/helm/values-staging.yaml \
#                          --set image.repository="$ECR_ENDPOINT/laa-apply-for-legal-aid/legal-framework-api" \
#                          --set image.tag="${CIRCLE_SHA1}"
#  hold_production_notification:
#    executor: notification-executor
#    steps:
#      - hold-notification:
#          message: "$CIRCLE_USERNAME has a pending LFA production approval for $CIRCLE_BRANCH"
#  deploy_production:
#    executor: cloud-platform-executor
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - *setup_kubectl
#      - run:
#          name: Set kubectl context
#          command: kubectl config use-context production
#      - *decrypt_secrets
#      - deploy:
#          name: Helm deployment to production
#          command: |
#            helm upgrade legal-framework-api ./deploy/helm/. \
#                        --install --wait \
#                        --namespace=${KUBE_ENV_PRODUCTION_NAMESPACE} \
#                        --values ./deploy/helm/values-production.yaml \
#                        --set image.repository="$ECR_ENDPOINT/laa-apply-for-legal-aid/legal-framework-api" \
#                        --set image.tag="${CIRCLE_SHA1}"
  clean_up_ecr:
    executor: linting-executor
    steps:
      - checkout
      - setup_remote_docker
      - *setup_aws_login
      - run:
          name: Delete old images from ecr repo
          command: |
            ./bin/clean_up_ecr
workflows:
  version: 2
  add_branch:
    jobs:
      - lint_checks:
          filters:
            branches:
              ignore: master
      - unit_tests:
          filters:
            branches:
              ignore: master
      - build_and_push:
          filters:
            branches:
              ignore: master
      - deploy_uat:
          requires:
            - lint_checks
            - unit_tests
            - build_and_push
  merge_pr:
    jobs:
      - lint_checks:
          filters:
            branches:
              only: master
      - unit_tests:
          filters:
            branches:
              only: master
#      - build_and_push:
#          requires:
#            - lint_checks
#            - unit_tests
#      - deploy_master_uat:
#          requires:
#            - build_and_push
#      - delete_uat_branch:
#          requires:
#            - deploy_master_uat
#      - deploy_staging:
#          requires:
#            - build_and_push
#      - hold_production_notification:
#          requires:
#            - delete_uat_branch
#            - deploy_staging
#      - hold_production:
#          type: approval
#          requires:
#            - delete_uat_branch
#            - deploy_staging
#      - deploy_production:
#          requires:
#            - hold_production
#  nightly:
#    triggers:
#      - schedule:
#          cron: "0 2 * * *"
#          filters:
#            branches:
#              only: master
#    jobs:
#      - clean_up_ecr
