version: 2.1

orbs:
  slack: circleci/slack@3.4.2
executors:
  basic-executor:
    docker:
      - image: cimg/base:2020.01
  cloud-platform-executor:
    docker:
      - image: ministryofjustice/cloud-platform-tools:1.24
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-apply-for-legal-aid
  linting-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - TZ: "Europe/London"
  test-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - PGHOST=localhost
          - PGUSER=user
          - TZ: "Europe/London"
      - image: postgres:10.5
        environment:
          - POSTGRES_USER=user
          - POSTGRES_DB=legal_framework_api_test

references:
  build_docker_image: &build_docker_image
    run:
      name: Build docker image
      command: |
        $(aws ecr get-login --no-include-email)
        docker build \
        --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
        --build-arg BUILD_TAG="app-${CIRCLE_SHA1}" \
        --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
        -t app .
  push_to_ecr: &push_to_ecr
    run:
      name: Push image to ecr repo
      command: |
        docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"
        docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "main" ]; then
          docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
          docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
        fi
  authenticate_k8s_uat: &authenticate_k8s_uat
    run:
      name: UAT - Authenticate with cluster
      command: |
        echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
        kubectl config set-credentials circleci --token=${K8S_UAT_TOKEN}
        kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_UAT_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER_NAME}
  authenticate_k8s_staging: &authenticate_k8s_staging
    run:
      name: Staging - Authenticate with cluster
      command: |
        echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
        kubectl config set-credentials circleci --token=${K8S_STAGING_TOKEN}
        kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_STAGING_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER_NAME}
  authenticate_k8s_production: &authenticate_k8s_production
    run:
      name: Production - Authenticate with cluster
      command: |
        echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
        kubectl config set-credentials circleci --token=${K8S_PRODUCTION_TOKEN}
        kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_PRODUCTION_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER_NAME}
  decrypt_secrets: &decrypt_secrets
    run:
      name: Decrypt secrets file
      command: |
        echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
        git-crypt unlock git-crypt.key
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      keys:
        - legal-framework-api-{{ checksum "Gemfile.lock" }}
        - legal-framework-api
  install_gems: &install_gems
    run:
      name: Install ruby gems
      command: |
        gem install bundler -v 2.0.2
        bundle install --without development --path=vendor/bundle --jobs=4 && bundle clean
  save_gems_cache: &save_gems_cache
    save_cache:
      key: legal-framework-api-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  install_packages_for_testing: &install_packages_for_testing
    run:
      name: Install System packages needed for testing
      command: sudo apt-get install -y postgresql-client
  setup_database: &setup_database
    run:
      name: Database Setup
      command: |
        bundle exec rake db:create db:schema:load
        bundle exec rake db:migrate

jobs:
  lint_checks:
    executor: linting-executor
    steps:
      - checkout
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - run:
          name: Run Rubocop
          command:  bin/rails rubocop
  unit_tests:
    executor: test-executor
    steps:
      - checkout
      - *install_packages_for_testing
      - *restore_gems_cache
      - *install_gems
      - *save_gems_cache
      - *setup_database
      - run:
          name: Run ruby tests
          command: bin/rails spec
  build_and_push:
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - *decrypt_secrets
      - *build_docker_image
      - *push_to_ecr
  deploy_uat: &deploy_uat
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *decrypt_secrets
      - *authenticate_k8s_uat
      - deploy:
          name: Helm deployment to UAT
          command: |
            echo "k8s authenticated"
            echo "Installing LFAPI helm chart"
            ./bin/uat_deploy
  deploy_main_uat:
    <<: *deploy_uat
  delete_uat_branch:
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker
      - *authenticate_k8s_uat
      - run:
          name: Delete UAT release
          command: |
            ./bin/delete_uat_release.sh
  deploy_staging:
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *decrypt_secrets
      - *authenticate_k8s_staging
      - deploy:
          name: Helm deployment to staging
          command: |
            helm upgrade legal-framework-api ./deploy/helm/. \
                          --install --wait \
                          --namespace=${K8S_STAGING_NAMESPACE} \
                          --values ./deploy/helm/values-staging.yaml \
                          --set image.repository="$ECR_ENDPOINT/laa-apply-for-legal-aid/legal-framework-api-uat-ecr" \
                          --set image.tag="${CIRCLE_SHA1}"
  deploy_production:
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *decrypt_secrets
      - *authenticate_k8s_production
      - deploy:
          name: Helm deployment to production
          command: |
            helm upgrade legal-framework-api ./deploy/helm/. \
                        --install --wait \
                        --namespace=${K8S_PRODUCTION_NAMESPACE} \
                        --values ./deploy/helm/values-production.yaml \
                        --set image.repository="$ECR_ENDPOINT/laa-apply-for-legal-aid/legal-framework-api-uat-ecr" \
                        --set image.tag="${CIRCLE_SHA1}"

workflows:
  new_pull_request:
    jobs:
      - lint_checks:
          filters:
            branches:
              ignore: main
      - unit_tests:
          filters:
            branches:
              ignore: main
      - build_and_push:
          filters:
            branches:
              ignore: main
      - deploy_uat:
          requires:
            - lint_checks
            - unit_tests
            - build_and_push

  merge_pr:
    jobs:
      - lint_checks:
          filters:
            branches:
              only: main
      - unit_tests:
          filters:
            branches:
              only: main
      - build_and_push:
          requires:
            - lint_checks
            - unit_tests
      - deploy_main_uat:
          requires:
            - build_and_push
      - delete_uat_branch:
          requires:
            - deploy_main_uat
      - deploy_staging:
          requires:
            - build_and_push
      - hold_production:
          type: approval
          requires:
            - delete_uat_branch
            - deploy_staging
      - deploy_production:
          requires:
            - hold_production
