version: 2.1

orbs:
  slack: circleci/slack@3.4.2
executors:
  basic-executor:
    docker:
      - image: cimg/base:2020.01
  cloud-platform-executor:
    docker:
      - image: ministryofjustice/cloud-platform-tools:1.23
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-apply-for-legal-aid
  linting-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - TZ: "Europe/London"
  notification-executor:
    docker:
      - image: 'cibuilds/base:latest'
        environment:
          TERM: dumb
    resource_class: small
  test-executor:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV=test
          - PGHOST=localhost
          - PGUSER=user
          - TZ: "Europe/London"
      - image: postgres:10.5
        environment:
          - POSTGRES_USER=user
          - POSTGRES_DB=legal_framework_api_test

references:
  build_docker_image: &build_docker_image
    run:
      name: Build application Docker image
        command: |
          $(aws ecr get-login --no-include-email)
          docker build \
          --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
          --build-arg BUILD_TAG="app-${CIRCLE_SHA1}" \
          --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
          -t app .
  push_to_ecr: &push_to_ecr
    run:
      name: Push image to ecr repo
      command: |
        docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"
        docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "main" ]; then
          docker tag app "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
          docker push "${ECR_ENDPOINT}/laa-apply-for-legal-aid/legal-framework-api-uat-ecr:latest"
        fi
  decrypt_secrets: &decrypt_secrets
    run:
      name: Decrypt secrets file
      command: |
        echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
        git-crypt unlock git-crypt.key

workflows:
  Build and deploy:
    jobs:
      - build:
          context: legal-framework-api-uat

jobs:
  build:
    docker:
      - image: ministryofjustice/cloud-platform-tools:1.23
        environment:
          IMAGE_URI: ${ECR_ENDPOINT}/legal-framework-api
    steps:
      - checkout
      - setup_remote_docker
      - *decrypt_secrets
      - *build_docker_image
      - *push_to_ecr
      - run:
          name: Authenticate with cluster
          command: |
            echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
            kubectl config set-credentials circleci --token=${K8S_TOKEN}
            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_NAMESPACE}
            kubectl config use-context ${K8S_CLUSTER_NAME}
      - run:
          name: Helm deployment to UAT
          command: |
            echo "Installing LFAPI helm chart"
            ./bin/uat_deploy
