require "swagger_helper"

RSpec.describe "merits_tasks", type: :request do
  path "/merits_tasks" do
    post("Return details of merits_tasks for specified proceeding types identified by CCMS-codes") do
      description "POST a JSON payload containing request-id (a UUID generated by the client) and an array
                   of proceeding types (identified by ccms_code) to
                   return a response containing the same request-id and an array of merits taks, grouped
                   by application and proceeding type. <br/><br/>
                   The tasks listed under application must be done once for the entire application, the tasks listed under
                   each proceeding type must be done once for each proceeding type.  Each task is specified as a key-value
                   pair where the key is the task name, and the value is the tasks on which it is dependent, or an empty array
                   if it is not dependent on any other tasks. <br/><br/>
                   In the given example, proceeding type SE014 has three tasks, namely:
                   <ul><li><code>chances_of_success</code></li>
                   <li><code>children_proceeding</code></li>
                   <li><code>attempts_to_settle</code></li></ul>.
                   The <code>children_proceeding</code> task is dependent upon the <code>children_application</code> task (which is in the
                   application group) being completed before this can be completed."

      let(:data) do
        {
          request_id: "7d47425b-800a-41ef-a917-934acc09b50d",
          proceeding_types: %w[DA005 SE004 SE013],
        }
      end

      tags "Merits tasks"
      consumes "application/json"
      produces "application/json"
      parameter name: :data,
                in: :body,
                schema: {
                  type: :object,
                  properties: {
                    request_id: { type: :string,
                                  example: "7d47425b-800a-41ef-a917-934acc09b50d",
                                  description: "Client generated request id that will be echoed back in the response" },
                    proceeding_types: { type: :array,
                                        items: { type: :string },
                                        example: %w[DA005 SE004 SE013],
                                        description: "Array of CCMS codes of proceeding types to  be queried" },
                  },
                  required: %w[request_id ccms_codes],
                }
      response(200, "success") do
        expected_successful_response =
          {
            request_id: "7d47425b-800a-41ef-a917-934acc09b50d",
            success: true,
            application: {
              tasks: {
                "latest_incident_details" => [],
                "opponent_name" => [],
                "opponent_mental_capacity" => [],
                "domestic_abuse_summary" => [],
                "statement_of_case" => [],
                "children_application" => [],
                "laspo" => [],
                "why_matter_opposed" => [],
              },
            },
            proceeding_types: [
              {
                ccms_code: "DA005",
                tasks: {
                  "chances_of_success" => [],
                  "opponents_application" => [],
                },
              },
              {
                ccms_code: "SE004",
                tasks: {
                  "chances_of_success" => [],
                  "children_proceeding" => %w[children_application],
                  "attempts_to_settle" => [],
                  "specific_issue" => [],
                  "opponents_application" => [],
                },
              },
              {
                ccms_code: "SE013",
                tasks: {
                  "chances_of_success" => [],
                  "children_proceeding" => %w[children_application],
                  "attempts_to_settle" => [],
                  "opponents_application" => [],
                },
              },
            ],
          }
        example "application/json",
                :success,
                expected_successful_response,
                "Successful request",
                "A request for three proceedings returns a set of tasks with dependencies"
        run_test! do |response|
          expect(response).to have_http_status(:success)
          expect(response.body).to eq expected_successful_response.to_json

          history = RequestHistory.find_by(request_id: "7d47425b-800a-41ef-a917-934acc09b50d")
          expect(history.request_method).to eq "POST"
          expect(history.endpoint).to eq "/merits_tasks"
          expect(history.request_payload).to eq data.to_json
          expect(history.response_status).to eq 200
          expect(history.response_payload).to eq expected_successful_response.to_json
        end
      end

      response(400, "bad request") do
        let(:data) do
          {
            request_id: "7d47425b-800a-41ef-a917-934acc09b50d",
            proceeding_types: %w[DA005 ZZ262 SE013],
          }
        end

        after do |example|
          example.metadata[:response][:content] = {
            "application/json": {
              examples: {
                bad_request: {
                  value: JSON.parse(response.body, symbolize_names: true),
                  summary: "Unsuccessful request",
                  description: "When invalid proceeding types are submitted an error will be raised and returned to the users",
                },
              },
            },
          }
        end

        run_test! do |response|
          expect(response).to have_http_status(:bad_request)
          expect(parsed_response[:request_id]).to eq "7d47425b-800a-41ef-a917-934acc09b50d"
          expect(parsed_response[:success]).to be false
          expect(parsed_response[:error_class]).to eq "ActiveRecord::RecordNotFound"
          expect(parsed_response[:message]).to match(/Couldn't find ProceedingType/)
        end
      end
    end
  end
end
