require "swagger_helper"

RSpec.describe "merits_tasks", type: :request, swagger: true do
  path "/merits_tasks" do
    post("Return details of merits_tasks for specified proceeding types identified by CCMS-codes") do
      description "POST a JSON payload containing request-id (a UUID generated by the client) and an array
                   of proceeding types (identified by ccms_code) to
                   return a response containing the same request-id and an array of merits taks, grouped
                   by application and proceeding type. <br/><br/>
                   The tasks listed under application must be done once for the entire application, the tasks listed under
                   each proceeding type must be done once for each proceeding type.  Each task is specified as a key-value
                   pair where the key is the task name, and the value is the tasks on which it is dependent, or an empty array
                   if it is not dependent on any other tasks. <br/><br/>
                   In the given example, proceeding type SE014 has three tasks, namely:
                   <ul><li><code>chances_of_success</code></li>
                   <li><code>children_proceeding</code></li>
                   <li><code>attempts_to_settle</code></li></ul>.
                   The <code>children_proceeding</code> task is dependent upon the <code>children_application</code> task (which is in the
                   application group) being completed before this can be completed."

      request_id = "7d47425b-800a-41ef-a917-934acc09b50d"
      proceeding_types = %w[DA001 DA003 SE014]

      tags "Merits tasks"
      response(200, "successful") do
        consumes "application/json"
        produces "application/json"
        parameter name: "threshold_waiver_query",
                  in: :body,
                  schema: {
                    type: :object,
                    properties: {
                      request_id: { type: :string,
                                    example: request_id,
                                    description: "Client generated request id that will be echoed back in the response" },
                      proceeding_types: { type: :array,
                                          items: { type: :string },
                                          example: proceeding_types,
                                          description: "Array of CCMS codes of proceeding types to  be queried" },
                    },
                    required: %w[request_id ccms_codes],
                  }
        response(200, "success") do
          seed_live_data
          response = MeritsTaskService.call(request_id, proceeding_types)

          examples "application/json" => response
          run_test!
        end
      end
    end
  end
end
