---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: legal-framework-api-staging.cloud-platform.service.justice.gov.uk/
