# Default values for legal-framework-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

ingress:
  className: default
  hosts:
    - legal-framework-api.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "legal-framework-api-legal-framework-api-production-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"

deploy:
  host: legal-framework-api.cloud-platform.service.justice.gov.uk

postgresql:
  enabled: false
