---
# list of all proceeding types and what scheme they belong to
:proceeding_types:
  SE013: :section_8_base
  SE014: :section_8_base
  SE015: :section_8_base
  SE003: :section_8_base
  SE004: :section_8_base
  SE016: :section_8_base
  SE095: :section_8_base
  SE007: :section_8_base
  SE008: :section_8_base
  SE097: :section_8_base
  SE014E: :section_8_enforcements
  SE013E: :section_8_enforcements
  SE015E: :section_8_enforcements
  SE100E: :section_8_enforcements
  SE003E: :section_8_enforcements
  SE096E: :section_8_enforcements
  SE004E: :section_8_enforcements
  SE099E: :section_8_enforcements
  SE016E: :section_8_enforcements
  SE007E: :section_8_enforcements
  SE008E: :section_8_enforcements
  SE101E: :section_8_enforcements
  SE013A: :section_8_appeals
  SE014A: :section_8_appeals
  SE015A: :section_8_appeals
  SE003A: :section_8_appeals
  SE004A: :section_8_appeals
  SE007A: :section_8_appeals
  SE008A: :section_8_appeals
  SE095A: :section_8_appeals
  SE097A: :section_8_appeals
  SE101A: :section_8_appeals
  SE016A: :section_8_appeals
  DA004: :domestic_abuse
  DA001: :domestic_abuse
  DA002: :domestic_abuse
  DA003: :domestic_abuse
  DA005: :domestic_abuse
  DA006: :domestic_abuse
  DA007: :domestic_abuse
  DA020: :domestic_abuse
  PB003: :special_children_act
  PB004: :special_children_act
  PB005: :special_children_act
  PB006: :special_children_act
  PB007: :special_children_act
  PB012: :special_children_act
  PB014: :special_children_act
  PB019: :special_children_act
  PB020: :special_children_act
  PB021: :special_children_act
  PB022: :special_children_act
  PB023: :special_children_act
  PB024: :special_children_act
  PB026: :special_children_act
  PB027: :special_children_act
  PB029: :special_children_act
  PB030: :special_children_act
  PB051: :special_children_act
  PB052: :special_children_act
  PB057: :special_children_act
  PB059: :special_children_act

# schemes
:schemes:
  :domestic_abuse:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - AA009
          - AA019
          - CV027
          - CV079
          - CV117
          - CV118
          - FM054
        :defaults:
          :cit_a: AA019
          :non_cit_a: AA019
      :delegated_functions:
        :scopes:
          - AA009
          - CV027
          - CV079
          - CV117
          - CV118
          - FM054
        :defaults:
          :cit_a: CV117
          :non_cit_a: CV118
  :section_8_base:
    :default_service_level: 1
    :service_level_1:
      :substantive:
        :scopes:
          - CV027
          - CV079
          - CV117
          - CV118
          - FM004
          - FM007
          - FM015
          - FM019
          - FM059
        :defaults:
          :cit_a: FM059
          :non_cit_a: FM059
      :delegated_functions:
        :scopes:
          - CV027
          - CV079
          - CV117
          - CV118
          - FM004
          - FM007
          - FM015
          - FM019
        :defaults:
          :cit_a: CV117
          :non_cit_a: CV118
    :service_level_3:
      :substantive:
        :scopes:
          - CV027
          - CV117
          - CV118
          - FM007
          - FM019
          - FM039
          - FM049
        :defaults:
          :cit_a: FM049
          :non_cit_a: FM049
      :delegated_functions:
        :scopes:
          - CV027
          - CV117
          - CV118
          - FM007
          - FM019
          - FM039
          - FM049
        :defaults:
          :cit_a: CV117
          :non_cit_a: CV118
  :section_8_appeals:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - APL07
          - APL09
          - APL11
          - APL13
          - APL15
          - APL16
          - APL18
          - APL20
          - APL22
          - APL27
          - APL29
          - APL31
          - APL48
          - APL49
          - APL50
          - APL51
          - APL52
          - APL53
          - APL54
          - APL55
          - APL56
          - APL57
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV027
          - CV079
          - CV118
        :defaults:
          :cit_a: CV079
          :non_cit_a: CV079
      :delegated_functions:
        :scopes:
          - APL07
          - APL09
          - APL11
          - APL13
          - APL15
          - APL16
          - APL18
          - APL20
          - APL22
          - APL27
          - APL29
          - APL31
          - APL48
          - APL49
          - APL50
          - APL51
          - APL52
          - APL53
          - APL54
          - APL55
          - APL56
          - APL57
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV027
          - CV079
          - CV118
        :defaults:
          :cit_a: CV118
          :non_cit_a: CV118
  :section_8_enforcements:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV027
          - CV118
          - EF012
          - EF022
          - EF025
          - EF026
          - EF027
          - FM019
          - FM049
          - MC029
        :defaults:
          :cit_a: FM019
          :non_cit_a: FM019
      :delegated_functions:
        :scopes:
          - CV027
          - CV118
          - EF012
          - EF022
          - EF025
          - EF026
          - EF027
          - FM019
          - FM049
          - MC029
        :defaults:
          :cit_a: FM019
          :non_cit_a: FM019
  :special_children_act:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV118
          - FM062
        :defaults:
          :cit_a: FM062
          :non_cit_a: FM062
      :delegated_functions:
        :scopes:
          - CV118
          - FM062
        :defaults:
          :cit_a: FM062
          :non_cit_a: FM062
