---
# list of all proceeding types and what scheme they belong to
:proceeding_types:
  SE013: :section_8_base
  SE014: :section_8_base
  SE015: :section_8_base
  SE003: :section_8_base
  SE004: :section_8_base
  SE016: :section_8_base
  SE095: :section_8_base
  SE007: :section_8_base
  SE008: :section_8_base
  SE097: :section_8_base
  SE014E: :section_8_enforcements
  SE013E: :section_8_enforcements
  SE015E: :section_8_enforcements
  SE100E: :section_8_enforcements
  SE003E: :section_8_enforcements
  SE096E: :section_8_enforcements
  SE004E: :section_8_enforcements
  SE016E: :section_8_enforcements
  SE007E: :section_8_enforcements
  SE008E: :section_8_enforcements
  SE101E: :section_8_enforcements
  SE013A: :section_8_appeals
  SE014A: :section_8_appeals
  SE015A: :section_8_appeals
  SE003A: :section_8_appeals
  SE004A: :section_8_appeals
  SE007A: :section_8_appeals
  SE008A: :section_8_appeals
  SE095A: :section_8_appeals
  SE097A: :section_8_appeals
  SE101A: :section_8_appeals
  SE016A: :section_8_appeals
  DA004: :domestic_abuse
  DA001: :domestic_abuse
  DA002: :domestic_abuse
  DA003: :domestic_abuse
  DA005: :domestic_abuse
  DA006: :domestic_abuse
  DA007: :domestic_abuse
  DA020: :domestic_abuse
  PB003: :special_children_act
  PB004: :special_children_act
  PB005: :special_children_act
  PB006: :special_children_act
  PB007: :special_children_act
  PB012: :special_children_act
  PB014: :special_children_act
  PB019: :special_children_act
  PB020: :special_children_act
  PB021: :special_children_act
  PB022: :special_children_act
  PB023: :special_children_act
  PB024: :special_children_act
  PB026: :special_children_act
  PB027: :special_children_act
  PB029: :special_children_act
  PB030: :special_children_act
  PB051: :special_children_act
  PB052: :special_children_act
  PB057: :special_children_act
  PB059: :special_children_act
  PBM01: :public_law_family_child_applicant_option
  PBM02: :public_law_family_child_applicant_option
  PBM04: :public_law_family_child_applicant_option
  PBM05: :public_law_family_child_applicant_option
  PBM06: :public_law_family_child_applicant_option
  PBM07: :public_law_family_child_applicant_option
  PBM08: :public_law_family_child_applicant_option
  PBM09: :public_law_family_child_applicant_option
  PBM10: :public_law_family_child_applicant_option
  PBM11: :public_law_family_child_applicant_option
  PBM13: :public_law_family_child_applicant_option
  PBM16: :public_law_family_child_applicant_option
  PBM17: :public_law_family_child_applicant_option
  PBM18: :public_law_family_child_applicant_option
  PBM19: :public_law_family_child_applicant_option
  PBM20: :public_law_family_child_applicant_option
  PBM21: :public_law_family_child_applicant_option
  PBM22: :public_law_family_child_applicant_option
  PBM23: :public_law_family_child_applicant_option
  PBM24: :public_law_family_child_applicant_option
  PBM26: :public_law_family_child_applicant_option
  PBM27: :public_law_family_child_applicant_option
  PBM28: :public_law_family_child_applicant_option
  PBM29: :public_law_family_child_applicant_option
  PBM30: :public_law_family_child_applicant_option
  PBM32: :public_law_family_child_applicant_option
  PBM33: :public_law_family_child_applicant_option
  PBM35: :public_law_family_child_applicant_option
  PBM36: :public_law_family_child_applicant_option
  PBM37: :public_law_family_child_applicant_option
  PBM38: :public_law_family_child_applicant_option
  PBM39: :public_law_family_child_applicant_option
  PBM45: :public_law_family_child_applicant_option
  PBM40: :public_law_family_placement_order
  PBM01A: :public_law_family_appeals
  PBM02A: :public_law_family_appeals
  PBM04A: :public_law_family_appeals
  PBM05A: :public_law_family_appeals
  PBM06A: :public_law_family_appeals
  PBM07A: :public_law_family_appeals
  PBM08A: :public_law_family_appeals
  PBM09A: :public_law_family_appeals
  PBM10A: :public_law_family_appeals
  PBM11A: :public_law_family_appeals
  PBM13A: :public_law_family_appeals
  PBM16A: :public_law_family_appeals
  PBM17A: :public_law_family_appeals
  PBM18A: :public_law_family_appeals
  PBM19A: :public_law_family_appeals
  PBM20A: :public_law_family_appeals
  PBM21A: :public_law_family_appeals
  PBM22A: :public_law_family_appeals
  PBM23A: :public_law_family_appeals
  PBM24A: :public_law_family_appeals
  PBM26A: :public_law_family_appeals
  PBM27A: :public_law_family_appeals
  PBM28A: :public_law_family_appeals
  PBM29A: :public_law_family_appeals
  PBM30A: :public_law_family_appeals
  PBM32A: :public_law_family_appeals
  PBM33A: :public_law_family_appeals
  PBM35A: :public_law_family_appeals
  PBM36A: :public_law_family_appeals
  PBM37A: :public_law_family_appeals
  PBM38A: :public_law_family_appeals
  PBM39A: :public_law_family_appeals
  PBM02E: :public_law_family_enforcement_base
  PBM04E: :public_law_family_enforcement_base
  PBM05E: :public_law_family_enforcement_base
  PBM06E: :public_law_family_enforcement_base
  PBM07E: :public_law_family_enforcement_base
  PBM08E: :public_law_family_enforcement_base
  PBM09E: :public_law_family_enforcement_base
  PBM11E: :public_law_family_enforcement_base
  PBM16E: :public_law_family_enforcement_base
  PBM17E: :public_law_family_enforcement_base
  PBM18E: :public_law_family_enforcement_base
  PBM19E: :public_law_family_enforcement_base
  PBM20E: :public_law_family_enforcement_base
  PBM21E: :public_law_family_enforcement_base
  PBM23E: :public_law_family_enforcement_base
  PBM24E: :public_law_family_enforcement_base
  PBM26E: :public_law_family_enforcement_base
  PBM27E: :public_law_family_enforcement_base
  PBM29E: :public_law_family_enforcement_base
  PBM30E: :public_law_family_enforcement_base
  PBM32E: :public_law_family_enforcement_base
  PBM33E: :public_law_family_enforcement_base
  PBM35E: :public_law_family_enforcement_base
  PBM36E: :public_law_family_enforcement_base
  PBM37E: :public_law_family_enforcement_base
  PBM38E: :public_law_family_enforcement_base
  PBM39E: :public_law_family_enforcement_base
  PBM40E: :public_law_family_enforcement_orders
  PBM45E: :public_law_family_enforcement_orders

# schemes
:schemes:
  :domestic_abuse:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - AA009
          - AA019
          - CV027
          - CV079
          - CV117
          - CV118
          - FM054
        :defaults:
          :default: AA019
      :delegated_functions:
        :scopes:
          - AA009
          - CV027
          - CV079
          - CV117
          - CV118
          - FM054
        :defaults:
          :cit_a: CV117
          :default: CV118
  :section_8_base:
    :default_service_level: 1
    :service_level_1:
      :substantive:
        :scopes:
          - CV027
          - CV079
          - CV117
          - CV118
          - FM004
          - FM007
          - FM015
          - FM019
          - FM059
        :defaults:
          :default: FM059
      :delegated_functions:
        :scopes:
          - CV027
          - CV079
          - CV117
          - CV118
          - FM004
          - FM007
          - FM015
          - FM019
        :defaults:
          :cit_a: CV117
          :default: CV118
    :service_level_3:
      :substantive:
        :scopes:
          - CV027
          - CV117
          - CV118
          - FM007
          - FM019
          - FM039
          - FM049
        :defaults:
          :default: FM049
      :delegated_functions:
        :scopes:
          - CV027
          - CV117
          - CV118
          - FM007
          - FM019
          - FM039
          - FM049
        :defaults:
          :cit_a: CV117
          :default: CV118
  :section_8_appeals:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - APL07
          - APL09
          - APL11
          - APL13
          - APL15
          - APL16
          - APL18
          - APL20
          - APL22
          - APL27
          - APL29
          - APL31
          - APL48
          - APL49
          - APL50
          - APL51
          - APL52
          - APL53
          - APL54
          - APL55
          - APL56
          - APL57
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV027
          - CV079
          - CV118
        :defaults:
          :default: CV079
      :delegated_functions:
        :scopes:
          - APL07
          - APL09
          - APL11
          - APL13
          - APL15
          - APL16
          - APL18
          - APL20
          - APL22
          - APL27
          - APL29
          - APL31
          - APL48
          - APL49
          - APL50
          - APL51
          - APL52
          - APL53
          - APL54
          - APL55
          - APL56
          - APL57
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV027
          - CV079
          - CV118
        :defaults:
          :default: CV118
  :section_8_enforcements:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV027
          - CV118
          - EF012
          - EF022
          - EF025
          - EF026
          - EF027
          - FM019
          - FM049
          - MC029
        :defaults:
          :default: FM019
      :delegated_functions:
        :scopes:
          - CV027
          - CV118
          - EF012
          - EF022
          - EF025
          - EF026
          - EF027
          - FM019
          - FM049
          - MC029
        :defaults:
          :default: FM019
  :special_children_act:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV118
          - FM062
        :defaults:
          :default: FM062
      :delegated_functions:
        :scopes:
          - CV118
          - FM062
        :defaults:
          :default: FM062
  :public_law_family_child_applicant_option:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - FM019
          - CV118
          - CV079
          - FM007
          - FM062
          - CV027
        :defaults:
          :cit_w: FM062
          :default: FM019
      :delegated_functions:
        :scopes:
          - FM019
          - CV118
          - CV079
          - FM007
          - FM062
          - CV027
        :defaults:
          :default: CV118
  :public_law_family_placement_order:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV118
          - FM062
          - EF025
          - EF026
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: FM062
      :delegated_functions:
        :scopes:
          - CV118
          - FM062
          - EF025
          - EF026
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: CV118
  :public_law_family_appeals:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - APL48
          - APL09
          - APL49
          - APL11
          - APL50
          - APL13
          - APL51
          - APL15
          - APL16
          - APL52
          - APL18
          - APL53
          - APL20
          - APL54
          - APL22
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV118
          - CV079
          - CV027
        :defaults:
          :default: CV079
      :delegated_functions:
        :scopes:
          - APL48
          - APL09
          - APL49
          - APL11
          - APL50
          - APL13
          - APL51
          - APL15
          - APL16
          - APL52
          - APL18
          - APL53
          - APL20
          - APL54
          - APL22
          - APL65
          - APL66
          - APL67
          - APL68
          - APL69
          - APL70
          - CV118
          - CV079
          - CV027
        :defaults:
          :default: CV118
  :public_law_family_enforcement_base:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV118
          - EF025
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: FM019
      :delegated_functions:
        :scopes:
          - CV118
          - EF025
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: EF025
  :public_law_family_enforcement_orders:
    :default_service_level: 3
    :service_level_3:
      :substantive:
        :scopes:
          - CV118
          - FM062
          - EF025
          - EF026
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: CV118
      :delegated_functions:
        :scopes:
          - CV118
          - FM062
          - EF025
          - EF026
          - EF022
          - CV027
          - FM019
        :defaults:
          :default: FM062
