name: Create Jira Ticket

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - test-gajira

jobs:
  create_jira_ticket:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.user.login, 'dependabot') }}

    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Log PR Author
        run: echo "PR Author ${{ github.event.pull_request.user.login }}"

      - name: Log PR Label
        run: echo "PR Label ${{ github.event.pull_request.labels.*.name }}"

      - name: Create Jira Ticket
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: AP
          issuetype: Maintenance
          summary: "Dependabot PR in ${{ github.repository }}: ${{ github.event.pull_request.title }}"
          description: ${{ github.event.pull_request.body }}
