name: Scan docker image
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scan-docker-image:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/snyk.yml@main
    with:
      tag: "legal-framework-application"
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
