name: Scan docker image
on:
  schedule:
    - cron: '0 5 * * *'

permissions: {}

jobs:
  scan-docker-image:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/snyk.yml@main
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    with:
      tag: "legal-framework-application"
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
